### ISSUE TITLE
modem speed?

### ISSUE THREAD

**Issue by rampa069** [ducasp/ESP8266-UNAPI-Firmware#3]
In the code, i cna see that the serial speed is 859372.  but this speed is at 80Mhz isnt it? i assume the real uart speed is twice (because of the 160MHZ stated in the readme) is this correct?

**Comment by rampa069** [comment]
no, the baud rate is consistent with both cpu speeds.... i can monitor it now.

**Comment by ducasp** [comment]
May I suggest that you contact through e-mail to make questions? Don't think that opening issues for that is effective, don't get me wrong, if issues are found this is the right place to do it and I welcome bug reports since they help improving things :)

Anyway, like you've figured out, CPU speed doesn't mess with peripherals. There is a single clock source that will generate either 80 or 160MHz for the CPU and also derive the peripherals clock. So peripherals timing doesn't change at all and they behave as programmed. :)

For e-mail contact it is the same name from github at gmail 👍
